/**
 * Seed dataset for offline / showcase mode.
 * Used as a graceful fallback when the backend is unreachable so the
 * UI remains fully explorable without any external dependencies.
 */
import type {
  AuditLog,
  Department,
  DocumentChunk,
  KBDocument,
  DocumentStats,
  EvalDatasetItem,
  EvalResult,
  GraphData,
  GraphPathResult,
  GraphStats,
  QAMessage,
  QASession,
  RetrievalExplain,
  RetrievalResult,
  SystemStats,
  User,
} from './types';

export const seedUser: User = {
  id: 'u-admin',
  email: 'hezh@semitech.cn',
  name: '贺哲华',
  role: 'admin',
  department_id: 'd-root',
  department_name: '集团总部',
  is_active: true,
  created_at: '2025-09-01T08:00:00Z',
  last_login_at: '2026-07-23T01:12:00Z',
};

export const seedUsers: User[] = [
  seedUser,
  {
    id: 'u-li',
    email: 'li.qiang@semitech.cn',
    name: '李强',
    role: 'editor',
    department_id: 'd-rd',
    department_name: '研发中心',
    is_active: true,
    created_at: '2025-10-12T08:00:00Z',
    last_login_at: '2026-07-22T14:30:00Z',
  },
  {
    id: 'u-wang',
    email: 'wang.min@semitech.cn',
    name: '王敏',
    role: 'editor',
    department_id: 'd-qa',
    department_name: '质量保证部',
    is_active: true,
    created_at: '2025-11-03T08:00:00Z',
    last_login_at: '2026-07-21T09:45:00Z',
  },
  {
    id: 'u-zhao',
    email: 'zhao.lei@semitech.cn',
    name: '赵磊',
    role: 'viewer',
    department_id: 'd-proc',
    department_name: '采购部',
    is_active: false,
    created_at: '2026-01-20T08:00:00Z',
    last_login_at: '2026-06-15T16:00:00Z',
  },
];

export const seedDepartments: Department[] = [
  {
    id: 'd-root',
    name: '集团总部',
    parent_id: null,
    code: 'HQ',
    member_count: 12,
    children: [
      {
        id: 'd-rd',
        name: '研发中心',
        parent_id: 'd-root',
        code: 'RD',
        member_count: 48,
        children: [
          { id: 'd-rd-fw', name: '固件组', parent_id: 'd-rd', code: 'RD-FW', member_count: 16 },
          { id: 'd-rd-sw', name: '软件组', parent_id: 'd-rd', code: 'RD-SW', member_count: 22 },
        ],
      },
      {
        id: 'd-qa',
        name: '质量保证部',
        parent_id: 'd-root',
        code: 'QA',
        member_count: 20,
      },
      {
        id: 'd-proc',
        name: '采购部',
        parent_id: 'd-root',
        code: 'PROC',
        member_count: 9,
      },
    ],
  },
];

const now = Date.now();
const day = 86_400_000;
const iso = (offsetDays: number) => new Date(now - offsetDays * day).toISOString();

export const seedDocuments: KBDocument[] = [
  // ==================== 企业知识库（工厂体系认证 / 制度 / 政策 / 通知） ====================
  {
    id: 'doc-1',
    title: 'ISO 9001 质量管理体系认证证书',
    filename: 'ISO9001-certificate-2026.pdf',
    format: 'pdf',
    size: 2_410_882,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '体系认证',
    status: 'ready',
    progress: 100,
    chunk_count: 86,
    uploaded_by: '陈工',
    created_at: iso(45),
    updated_at: iso(20),
  },
  {
    id: 'doc-2',
    title: 'ISO 14001 环境管理体系认证证书',
    filename: 'ISO14001-certificate-2026.pdf',
    format: 'pdf',
    size: 1_982_330,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '体系认证',
    status: 'ready',
    progress: 100,
    chunk_count: 72,
    uploaded_by: '陈工',
    created_at: iso(42),
    updated_at: iso(18),
  },
  {
    id: 'doc-3',
    title: 'ISO 45001 职业健康安全管理体系认证证书',
    filename: 'ISO45001-certificate-2026.pdf',
    format: 'pdf',
    size: 2_120_440,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '体系认证',
    status: 'ready',
    progress: 100,
    chunk_count: 68,
    uploaded_by: '陈工',
    created_at: iso(40),
    updated_at: iso(16),
  },
  {
    id: 'doc-4',
    title: 'BSCI 社会责任审核报告 2025',
    filename: 'BSCI-audit-report-2025.pdf',
    format: 'pdf',
    size: 5_204_117,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '体系认证',
    status: 'ready',
    progress: 100,
    chunk_count: 134,
    uploaded_by: '陈工',
    created_at: iso(38),
    updated_at: iso(12),
  },
  {
    id: 'doc-5',
    title: 'IATF 16949 汽车质量管理体系认证证书',
    filename: 'IATF16949-certificate-2026.pdf',
    format: 'pdf',
    size: 3_820_660,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '体系认证',
    status: 'ready',
    progress: 100,
    chunk_count: 118,
    uploaded_by: '陈工',
    created_at: iso(36),
    updated_at: iso(14),
  },
  {
    id: 'doc-6',
    title: 'QC 080000 有害物质过程管理体系认证证书',
    filename: 'QC080000-certificate-2026.pdf',
    format: 'pdf',
    size: 1_640_220,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '体系认证',
    status: 'ready',
    progress: 100,
    chunk_count: 64,
    uploaded_by: '陈工',
    created_at: iso(34),
    updated_at: iso(13),
  },
  {
    id: 'doc-7',
    title: 'ANSI/ESD S20.20 静电放电控制体系认证证书',
    filename: 'ESD-S20.20-certificate-2026.pdf',
    format: 'pdf',
    size: 1_240_440,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '体系认证',
    status: 'parsing',
    progress: 78,
    chunk_count: 0,
    uploaded_by: '陈工',
    created_at: iso(1),
    updated_at: iso(0),
  },
  {
    id: 'doc-8',
    title: 'ISO 50001 能源管理体系认证证书',
    filename: 'ISO50001-certificate-2026.pdf',
    format: 'pdf',
    size: 1_482_330,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '体系认证',
    status: 'ready',
    progress: 100,
    chunk_count: 58,
    uploaded_by: '陈工',
    created_at: iso(32),
    updated_at: iso(11),
  },
  {
    id: 'doc-9',
    title: '供应商准入管理办法',
    filename: 'supplier-qualification-management.pdf',
    format: 'pdf',
    size: 1_120_440,
    department_id: 'd-proc',
    department_name: '采购部',
    category: '管理制度',
    status: 'ready',
    progress: 100,
    chunk_count: 76,
    uploaded_by: '赵磊',
    created_at: iso(28),
    updated_at: iso(9),
  },
  {
    id: 'doc-10',
    title: '可靠性测试规范',
    filename: 'reliability-test-specification.pdf',
    format: 'pdf',
    size: 2_820_660,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '技术规范',
    status: 'ready',
    progress: 100,
    chunk_count: 142,
    uploaded_by: '王敏',
    created_at: iso(30),
    updated_at: iso(10),
  },
  {
    id: 'doc-11',
    title: '来料检验规范',
    filename: 'incoming-inspection-specification.pdf',
    format: 'pdf',
    size: 1_640_880,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '技术规范',
    status: 'ready',
    progress: 100,
    chunk_count: 88,
    uploaded_by: '王敏',
    created_at: iso(26),
    updated_at: iso(8),
  },
  {
    id: 'doc-12',
    title: '失效分析管理办法',
    filename: 'failure-analysis-management.pdf',
    format: 'pdf',
    size: 1_320_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '管理制度',
    status: 'ready',
    progress: 100,
    chunk_count: 72,
    uploaded_by: '李强',
    created_at: iso(24),
    updated_at: iso(7),
  },
  {
    id: 'doc-13',
    title: 'ECN 工程变更通知管理程序',
    filename: 'ECN-change-control-procedure.pdf',
    format: 'pdf',
    size: 980_660,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '管理制度',
    status: 'ready',
    progress: 100,
    chunk_count: 54,
    uploaded_by: '李强',
    created_at: iso(22),
    updated_at: iso(6),
  },
  {
    id: 'doc-14',
    title: '文件控制程序',
    filename: 'document-control-procedure.pdf',
    format: 'pdf',
    size: 820_440,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '管理制度',
    status: 'ready',
    progress: 100,
    chunk_count: 48,
    uploaded_by: '王敏',
    created_at: iso(33),
    updated_at: iso(12),
  },
  {
    id: 'doc-15',
    title: '记录控制程序',
    filename: 'record-control-procedure.pdf',
    format: 'pdf',
    size: 712_330,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '管理制度',
    status: 'ready',
    progress: 100,
    chunk_count: 42,
    uploaded_by: '王敏',
    created_at: iso(31),
    updated_at: iso(11),
  },
  {
    id: 'doc-16',
    title: '内部审核程序',
    filename: 'internal-audit-procedure.pdf',
    format: 'pdf',
    size: 1_024_660,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '管理制度',
    status: 'ready',
    progress: 100,
    chunk_count: 62,
    uploaded_by: '王敏',
    created_at: iso(29),
    updated_at: iso(10),
  },
  {
    id: 'doc-17',
    title: '管理评审程序',
    filename: 'management-review-procedure.pdf',
    format: 'pdf',
    size: 684_220,
    department_id: 'd-root',
    department_name: '集团总部',
    category: '管理制度',
    status: 'ready',
    progress: 100,
    chunk_count: 36,
    uploaded_by: '贺哲华',
    created_at: iso(35),
    updated_at: iso(13),
  },
  {
    id: 'doc-18',
    title: '纠正预防措施程序',
    filename: 'corrective-preventive-action-procedure.pdf',
    format: 'pdf',
    size: 1_120_440,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '管理制度',
    status: 'ready',
    progress: 100,
    chunk_count: 58,
    uploaded_by: '王敏',
    created_at: iso(27),
    updated_at: iso(9),
  },
  {
    id: 'doc-19',
    title: '2026 年质量目标',
    filename: '2026-quality-objectives.pdf',
    format: 'pdf',
    size: 524_220,
    department_id: 'd-root',
    department_name: '集团总部',
    category: '政策文件',
    status: 'ready',
    progress: 100,
    chunk_count: 32,
    uploaded_by: '贺哲华',
    created_at: iso(44),
    updated_at: iso(18),
  },
  {
    id: 'doc-20',
    title: '出口管制合规政策',
    filename: 'export-control-compliance-policy.pdf',
    format: 'pdf',
    size: 1_482_660,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '政策文件',
    status: 'ready',
    progress: 100,
    chunk_count: 76,
    uploaded_by: '陈工',
    created_at: iso(41),
    updated_at: iso(15),
  },
  {
    id: 'doc-21',
    title: '知识产权管理办法',
    filename: 'IP-management-policy.docx',
    format: 'docx',
    size: 712_340,
    department_id: 'd-root',
    department_name: '集团总部',
    category: '政策文件',
    status: 'ready',
    progress: 100,
    chunk_count: 38,
    uploaded_by: '贺哲华',
    created_at: iso(48),
    updated_at: iso(19),
  },
  {
    id: 'doc-22',
    title: '商业秘密保护规定',
    filename: 'trade-secret-protection.pdf',
    format: 'pdf',
    size: 612_440,
    department_id: 'd-root',
    department_name: '集团总部',
    category: '政策文件',
    status: 'ready',
    progress: 100,
    chunk_count: 34,
    uploaded_by: '贺哲华',
    created_at: iso(43),
    updated_at: iso(16),
  },
  {
    id: 'doc-23',
    title: '数据安全管理制度',
    filename: 'data-security-management-policy.docx',
    format: 'docx',
    size: 1_024_000,
    department_id: 'd-root',
    department_name: '集团总部',
    category: '政策文件',
    status: 'ready',
    progress: 100,
    chunk_count: 68,
    uploaded_by: '贺哲华',
    created_at: iso(35),
    updated_at: iso(11),
  },
  {
    id: 'doc-24',
    title: '产品召回管理办法',
    filename: 'product-recall-management.pdf',
    format: 'pdf',
    size: 920_440,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '政策文件',
    status: 'ready',
    progress: 100,
    chunk_count: 44,
    uploaded_by: '王敏',
    created_at: iso(40),
    updated_at: iso(15),
  },
  {
    id: 'doc-25',
    title: '2026 年 Q3 质量月活动通知',
    filename: '2026-Q3-quality-month-notice.docx',
    format: 'docx',
    size: 384_220,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '内部通知',
    status: 'pending',
    progress: 0,
    chunk_count: 0,
    uploaded_by: '王敏',
    created_at: iso(0),
    updated_at: iso(0),
  },
  {
    id: 'doc-26',
    title: 'IATF 16949 监督审核通知',
    filename: 'IATF16949-surveillance-audit-notice.docx',
    format: 'docx',
    size: 412_330,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '内部通知',
    status: 'ready',
    progress: 100,
    chunk_count: 24,
    uploaded_by: '陈工',
    created_at: iso(3),
    updated_at: iso(1),
  },
  {
    id: 'doc-27',
    title: '新版 RoHS 指令切换通知',
    filename: 'RoHS-directive-update-notice.docx',
    format: 'docx',
    size: 368_440,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '内部通知',
    status: 'ready',
    progress: 100,
    chunk_count: 22,
    uploaded_by: '陈工',
    created_at: iso(4),
    updated_at: iso(1),
  },
  {
    id: 'doc-28',
    title: '车规产品产线扩产通知',
    filename: 'automotive-production-line-expansion-notice.pdf',
    format: 'pdf',
    size: 524_660,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '内部通知',
    status: 'ready',
    progress: 100,
    chunk_count: 28,
    uploaded_by: '李强',
    created_at: iso(6),
    updated_at: iso(2),
  },
  {
    id: 'doc-29',
    title: '年度可靠性测试计划',
    filename: 'annual-reliability-test-plan.xlsx',
    format: 'xlsx',
    size: 682_440,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '内部通知',
    status: 'failed',
    progress: 20,
    chunk_count: 0,
    error_message: '解析失败：表格结构异常，合并单元格超出阈值',
    uploaded_by: '王敏',
    created_at: iso(5),
    updated_at: iso(1),
  },
  // ==================== 产品知识库（存储产品手册 / 技术规格 / 认证要求 / 选型） ====================
  {
    id: 'doc-30',
    title: '3D TLC NAND Flash 技术规格书',
    filename: '3D-TLC-NAND-Flash-specification.pdf',
    format: 'pdf',
    size: 5_820_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 168,
    uploaded_by: '李强',
    created_at: iso(19),
    updated_at: iso(5),
  },
  {
    id: 'doc-31',
    title: '3D QLC NAND Flash 技术规格书',
    filename: '3D-QLC-NAND-Flash-specification.pdf',
    format: 'pdf',
    size: 5_410_220,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 156,
    uploaded_by: '李强',
    created_at: iso(17),
    updated_at: iso(4),
  },
  {
    id: 'doc-32',
    title: 'SLC NAND Flash 工业级规格书',
    filename: 'SLC-NAND-Flash-industrial-specification.pdf',
    format: 'pdf',
    size: 3_240_880,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 112,
    uploaded_by: '李强',
    created_at: iso(23),
    updated_at: iso(7),
  },
  {
    id: 'doc-33',
    title: 'NAND Flash 可靠性测试报告',
    filename: 'NAND-Flash-reliability-test-report.pdf',
    format: 'pdf',
    size: 4_120_330,
    department_id: 'd-qa',
    department_name: '质量保证部',
    category: '可靠性报告',
    status: 'ready',
    progress: 100,
    chunk_count: 142,
    uploaded_by: '王敏',
    created_at: iso(21),
    updated_at: iso(6),
  },
  {
    id: 'doc-34',
    title: 'NAND Flash 失效分析指南',
    filename: 'NAND-Flash-failure-analysis-guide.pdf',
    format: 'pdf',
    size: 2_820_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '失效分析',
    status: 'ready',
    progress: 100,
    chunk_count: 96,
    uploaded_by: '李强',
    created_at: iso(12),
    updated_at: iso(3),
  },
  {
    id: 'doc-35',
    title: 'DDR5 DRAM 技术规格书',
    filename: 'DDR5-DRAM-specification.pdf',
    format: 'pdf',
    size: 4_820_660,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 148,
    uploaded_by: '李强',
    created_at: iso(18),
    updated_at: iso(5),
  },
  {
    id: 'doc-36',
    title: 'LPDDR5 DRAM 技术规格书',
    filename: 'LPDDR5-DRAM-specification.pdf',
    format: 'pdf',
    size: 4_204_880,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'parsing',
    progress: 88,
    chunk_count: 0,
    uploaded_by: '李强',
    created_at: iso(1),
    updated_at: iso(0),
  },
  {
    id: 'doc-37',
    title: 'DDR4 DRAM 桌面级规格书',
    filename: 'DDR4-DRAM-desktop-specification.pdf',
    format: 'pdf',
    size: 3_820_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 124,
    uploaded_by: '李强',
    created_at: iso(10),
    updated_at: iso(2),
  },
  {
    id: 'doc-38',
    title: 'DRAM 颗粒选型指南',
    filename: 'DRAM-particle-selection-guide.xlsx',
    format: 'xlsx',
    size: 1_282_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '选型指南',
    status: 'ready',
    progress: 100,
    chunk_count: 76,
    uploaded_by: '李强',
    created_at: iso(15),
    updated_at: iso(4),
  },
  {
    id: 'doc-39',
    title: 'eMMC 5.1 规格书',
    filename: 'eMMC-5.1-specification.pdf',
    format: 'pdf',
    size: 3_240_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 132,
    uploaded_by: '李强',
    created_at: iso(16),
    updated_at: iso(4),
  },
  {
    id: 'doc-40',
    title: 'UFS 3.1 规格书',
    filename: 'UFS-3.1-specification.pdf',
    format: 'pdf',
    size: 3_612_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 128,
    uploaded_by: '李强',
    created_at: iso(14),
    updated_at: iso(3),
  },
  {
    id: 'doc-41',
    title: '车规 eMMC 规格书（AEC-Q100）',
    filename: 'automotive-eMMC-AEC-Q100-specification.pdf',
    format: 'pdf',
    size: 4_120_660,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 156,
    uploaded_by: '李强',
    created_at: iso(13),
    updated_at: iso(3),
  },
  {
    id: 'doc-42',
    title: 'UFS 4.0 规格书',
    filename: 'UFS-4.0-specification.pdf',
    format: 'pdf',
    size: 3_820_220,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 134,
    uploaded_by: '李强',
    created_at: iso(11),
    updated_at: iso(2),
  },
  {
    id: 'doc-43',
    title: 'NVMe SSD 企业级规格书',
    filename: 'NVMe-SSD-enterprise-specification.pdf',
    format: 'pdf',
    size: 5_240_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 184,
    uploaded_by: '李强',
    created_at: iso(18),
    updated_at: iso(3),
  },
  {
    id: 'doc-44',
    title: 'SATA SSD 消费级规格书',
    filename: 'SATA-SSD-consumer-specification.pdf',
    format: 'pdf',
    size: 3_180_640,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 128,
    uploaded_by: '李强',
    created_at: iso(22),
    updated_at: iso(6),
  },
  {
    id: 'doc-45',
    title: '车规 SSD 规格书',
    filename: 'automotive-SSD-specification.pdf',
    format: 'pdf',
    size: 4_460_220,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 152,
    uploaded_by: '李强',
    created_at: iso(25),
    updated_at: iso(8),
  },
  {
    id: 'doc-46',
    title: 'SSD 固件升级手册',
    filename: 'SSD-firmware-upgrade-manual.pdf',
    format: 'pdf',
    size: 2_440_880,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '固件手册',
    status: 'ready',
    progress: 100,
    chunk_count: 96,
    uploaded_by: '李强',
    created_at: iso(28),
    updated_at: iso(10),
  },
  {
    id: 'doc-47',
    title: 'MCP 多芯片封装规格书',
    filename: 'MCP-multi-chip-package-specification.pdf',
    format: 'pdf',
    size: 2_920_440,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 112,
    uploaded_by: '李强',
    created_at: iso(20),
    updated_at: iso(7),
  },
  {
    id: 'doc-48',
    title: 'eMCP 规格书',
    filename: 'eMCP-specification.pdf',
    format: 'pdf',
    size: 2_620_660,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 104,
    uploaded_by: '李强',
    created_at: iso(26),
    updated_at: iso(9),
  },
  {
    id: 'doc-49',
    title: 'MicroSD 卡规格书',
    filename: 'MicroSD-card-specification.pdf',
    format: 'pdf',
    size: 1_680_220,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'parsing',
    progress: 78,
    chunk_count: 0,
    uploaded_by: '李强',
    created_at: iso(4),
    updated_at: iso(0),
  },
  {
    id: 'doc-50',
    title: 'SD 卡工业级规格书',
    filename: 'SD-card-industrial-specification.pdf',
    format: 'pdf',
    size: 2_240_880,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '产品规格书',
    status: 'ready',
    progress: 100,
    chunk_count: 116,
    uploaded_by: '李强',
    created_at: iso(20),
    updated_at: iso(7),
  },
  {
    id: 'doc-51',
    title: '存储产品全球认证要求清单（CE/RoHS/FCC/UKCA/REACH/KC/PSE/BSMI）',
    filename: 'storage-product-global-certification-matrix.xlsx',
    format: 'xlsx',
    size: 1_420_440,
    department_id: 'd-cmp',
    department_name: '合规认证部',
    category: '认证要求',
    status: 'ready',
    progress: 100,
    chunk_count: 88,
    uploaded_by: '陈工',
    created_at: iso(14),
    updated_at: iso(2),
  },
  // ==================== 售后知识库（FAQ / 保修 / 故障排查 / 退换货） ====================
  {
    id: 'doc-52',
    title: '存储芯片售后 FAQ 100 问',
    filename: 'storage-chip-after-sales-FAQ-100.pdf',
    format: 'pdf',
    size: 1_820_660,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '售后 FAQ',
    status: 'ready',
    progress: 100,
    chunk_count: 96,
    uploaded_by: '王敏',
    created_at: iso(9),
    updated_at: iso(1),
  },
  {
    id: 'doc-53',
    title: '车规 eMMC 售后 FAQ',
    filename: 'automotive-eMMC-after-sales-FAQ.pdf',
    format: 'pdf',
    size: 1_280_220,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '售后 FAQ',
    status: 'ready',
    progress: 100,
    chunk_count: 72,
    uploaded_by: '王敏',
    created_at: iso(16),
    updated_at: iso(4),
  },
  {
    id: 'doc-54',
    title: 'SSD 常见故障 FAQ',
    filename: 'SSD-common-fault-FAQ.pdf',
    format: 'pdf',
    size: 1_040_440,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '售后 FAQ',
    status: 'ready',
    progress: 100,
    chunk_count: 64,
    uploaded_by: '王敏',
    created_at: iso(12),
    updated_at: iso(3),
  },
  {
    id: 'doc-55',
    title: '售后通用术语手册',
    filename: 'after-sales-glossary-handbook.docx',
    format: 'docx',
    size: 682_440,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '售后 FAQ',
    status: 'ready',
    progress: 100,
    chunk_count: 48,
    uploaded_by: '贺哲华',
    created_at: iso(8),
    updated_at: iso(2),
  },
  {
    id: 'doc-56',
    title: '消费级存储产品保修条款',
    filename: 'consumer-storage-warranty-terms.pdf',
    format: 'pdf',
    size: 982_440,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '保修条款',
    status: 'ready',
    progress: 100,
    chunk_count: 56,
    uploaded_by: '王敏',
    created_at: iso(11),
    updated_at: iso(2),
  },
  {
    id: 'doc-57',
    title: '车规存储产品保修条款',
    filename: 'automotive-storage-warranty-terms.pdf',
    format: 'pdf',
    size: 1_120_220,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '保修条款',
    status: 'ready',
    progress: 100,
    chunk_count: 68,
    uploaded_by: '王敏',
    created_at: iso(13),
    updated_at: iso(3),
  },
  {
    id: 'doc-58',
    title: '企业级 SSD 保修与服务等级协议',
    filename: 'enterprise-SSD-warranty-SLA.pdf',
    format: 'pdf',
    size: 1_420_660,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '保修条款',
    status: 'ready',
    progress: 100,
    chunk_count: 84,
    uploaded_by: '贺哲华',
    created_at: iso(7),
    updated_at: iso(1),
  },
  {
    id: 'doc-59',
    title: 'NAND Flash 失效分析方法论',
    filename: 'NAND-Flash-failure-analysis-methodology.pdf',
    format: 'pdf',
    size: 1_460_220,
    department_id: 'd-rd',
    department_name: '研发中心',
    category: '故障排查',
    status: 'ready',
    progress: 100,
    chunk_count: 92,
    uploaded_by: '李强',
    created_at: iso(17),
    updated_at: iso(5),
  },
  {
    id: 'doc-60',
    title: 'eMMC 故障代码手册',
    filename: 'eMMC-fault-code-manual.pdf',
    format: 'pdf',
    size: 1_120_440,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '故障排查',
    status: 'ready',
    progress: 100,
    chunk_count: 72,
    uploaded_by: '王敏',
    created_at: iso(19),
    updated_at: iso(6),
  },
  {
    id: 'doc-61',
    title: 'SSD SMART 参数解读手册',
    filename: 'SSD-SMART-parameter-handbook.pdf',
    format: 'pdf',
    size: 980_660,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '故障排查',
    status: 'ready',
    progress: 100,
    chunk_count: 58,
    uploaded_by: '王敏',
    created_at: iso(21),
    updated_at: iso(7),
  },
  {
    id: 'doc-62',
    title: '退换货流程作业指导书',
    filename: 'return-exchange-process-work-instruction.pdf',
    format: 'pdf',
    size: 1_360_880,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '退换货',
    status: 'ready',
    progress: 100,
    chunk_count: 84,
    uploaded_by: '贺哲华',
    created_at: iso(15),
    updated_at: iso(4),
  },
  {
    id: 'doc-63',
    title: 'RMA 返修操作规范',
    filename: 'RMA-repair-operation-specification.pdf',
    format: 'pdf',
    size: 742_220,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '退换货',
    status: 'ready',
    progress: 100,
    chunk_count: 46,
    uploaded_by: '王敏',
    created_at: iso(24),
    updated_at: iso(8),
  },
  {
    id: 'doc-64',
    title: '客户服务响应规范',
    filename: 'customer-service-response-specification.pdf',
    format: 'pdf',
    size: 1_180_440,
    department_id: 'd-aftersales',
    department_name: '售后服务部',
    category: '退换货',
    status: 'pending',
    progress: 0,
    chunk_count: 0,
    uploaded_by: '赵磊',
    created_at: iso(2),
    updated_at: iso(0),
  },
];

export const seedDocumentStats: DocumentStats = {
  total: seedDocuments.length,
  parsing: seedDocuments.filter((d) => d.status === 'parsing').length,
  ready: seedDocuments.filter((d) => d.status === 'ready').length,
  failed: seedDocuments.filter((d) => d.status === 'failed').length,
  total_chunks: seedDocuments.reduce((s, d) => s + d.chunk_count, 0),
  total_size: seedDocuments.reduce((s, d) => s + d.size, 0),
};

export const seedChunks: DocumentChunk[] = [
  {
    id: 'chunk-1',
    document_id: 'doc-41',
    chunk_index: 0,
    heading_path: ['第 1 章', '1.1 产品概述'],
    page_number: 3,
    content:
      '车规 eMMC 5.1 是面向车载信息娱乐系统(IVI)与 ADAS 数据记录的 NAND Flash 存储器件，依据 AEC-Q100 标准进行车规认证。工作温度等级分为 Grade 3(-40~85℃)、Grade 2(-40~105℃)、Grade 1(-40~125℃)、Grade 0(-40~150℃)，车规 eMMC 通常要求 Grade 3 及以上。',
    token_count: 132,
    bm25_terms: ['车规 eMMC', 'AEC-Q100', '温度等级', 'Grade 3'],
  },
  {
    id: 'chunk-2',
    document_id: 'doc-41',
    chunk_index: 1,
    heading_path: ['第 3 章', '3.2 AEC-Q100 认证流程'],
    page_number: 18,
    content:
      'eMMC 5.1 的车规认证流程依据 AEC-Q100 分为四个阶段：晶圆级测试(Wafer Level Test)、封装级测试(Package Level Test)、可靠性认证(Reliability Certification，含 HTOL/TC/uHAST)与量产放行(PPAP)。完成全阶段后由车厂或 Tier1 审核 PPAP 文件包并签发量产批准。',
    token_count: 146,
    bm25_terms: ['AEC-Q100', '认证流程', '晶圆级测试', 'PPAP', '可靠性认证'],
  },
  {
    id: 'chunk-3',
    document_id: 'doc-9',
    chunk_index: 0,
    heading_path: ['Sheet1', 'NAND Flash 供应商清单'],
    page_number: 1,
    content:
      'NAND Flash 晶圆代工与封测合格供应商共 4 家：中芯国际(晶圆代工)、华虹半导体(晶圆代工)、长电科技(封测)、通富微电(封测)。其中中芯国际为主晶圆代工方，华虹半导体为二供；封测环节由长电科技与通富微电承接，均通过 IATF 16949 认证。',
    token_count: 118,
    bm25_terms: ['供应商', 'NAND Flash', '晶圆代工', 'IATF 16949', '中芯国际'],
  },
  {
    id: 'chunk-4',
    document_id: 'doc-10',
    chunk_index: 0,
    heading_path: ['第二章', '2.1 可靠性测试项目'],
    page_number: 5,
    content:
      '存储产品可靠性测试项目按 AEC-Q100 与 JEDEC 标准分为三类：寿命测试(HTOL 高温工作寿命、TC 温度循环)、环境测试(uHAST 非饱和高压蒸煮、THB 温湿度偏压)、机械测试(跌落、振动)。NVMe SSD 须额外执行端到端数据完整性校验与异常掉电测试。',
    token_count: 124,
    bm25_terms: ['可靠性测试', 'HTOL', '温度循环', 'uHAST', 'NVMe SSD'],
  },
];

export const seedSessions: QASession[] = [
  {
    id: 's-1',
    title: 'eMMC 5.1 车规认证咨询',
    user_id: 'u-admin',
    message_count: 4,
    last_message_at: iso(0),
    created_at: iso(1),
  },
  {
    id: 's-2',
    title: 'NAND Flash 供应商核查',
    user_id: 'u-admin',
    message_count: 2,
    last_message_at: iso(2),
    created_at: iso(3),
  },
  {
    id: 's-3',
    title: '可靠性测试项目咨询',
    user_id: 'u-admin',
    message_count: 2,
    last_message_at: iso(4),
    created_at: iso(5),
  },
];

export const seedMessages: Record<string, QAMessage[]> = {
  's-1': [
    {
      id: 'm-1',
      session_id: 's-1',
      role: 'user',
      content: '车规 eMMC 5.1 的 AEC-Q100 认证流程是怎样的？',
      created_at: iso(1),
    },
    {
      id: 'm-2',
      session_id: 's-1',
      role: 'assistant',
      content:
        '车规 eMMC 5.1 的 AEC-Q100 认证流程分为四个阶段：**晶圆级测试(Wafer Level Test)**、**封装级测试(Package Level Test)**、**可靠性认证(Reliability Certification)** 与**量产放行(PPAP)**。\n\n其中可靠性认证须依据 AEC-Q100 执行 HTOL 高温工作寿命、TC 温度循环、uHAST 非饱和高压蒸煮等测试项，工作温度等级须满足 Grade 3(-40~85℃) 及以上。完成全阶段后由车厂或 Tier1 审核 PPAP 文件包并签发量产批准。',
      citations: [
        {
          chunk_id: 'chunk-2',
          document_id: 'doc-41',
          document_title: '车规 eMMC 规格书（AEC-Q100）',
          heading_path: ['第 3 章', '3.2 AEC-Q100 认证流程'],
          page_number: 18,
          snippet:
            'eMMC 5.1 的车规认证流程依据 AEC-Q100 分为四个阶段：晶圆级测试、封装级测试、可靠性认证与量产放行(PPAP)……',
          score: 0.92,
          source: 'rerank',
        },
        {
          chunk_id: 'chunk-1',
          document_id: 'doc-41',
          document_title: '车规 eMMC 规格书（AEC-Q100）',
          heading_path: ['第 1 章', '1.1 产品概述'],
          page_number: 3,
          snippet:
            '车规 eMMC 5.1 是面向车载信息娱乐系统(IVI)与 ADAS 数据记录的 NAND Flash 存储器件，依据 AEC-Q100 标准进行车规认证，工作温度等级分为 Grade 3/2/1/0……',
          score: 0.81,
          source: 'rrf',
        },
      ],
      retrieval: {
        query: '车规 eMMC 5.1 的 AEC-Q100 认证流程是怎样的？',
        rewritten_query: '车规 eMMC 5.1 AEC-Q100 认证流程 晶圆级 封装级 可靠性 PPAP',
        cache_hit: false,
        total_latency_ms: 312,
        stages: [
          { stage: 'bm25', latency_ms: 28, recall: 0.74 },
          { stage: 'vector', latency_ms: 96, recall: 0.88 },
          { stage: 'rrf', latency_ms: 14, recall: 0.91 },
          { stage: 'rerank', latency_ms: 174, recall: 0.95 },
        ],
        chunks: [
          {
            chunk_id: 'chunk-2',
            document_id: 'doc-41',
            document_title: '车规 eMMC 规格书（AEC-Q100）',
            heading_path: ['第 3 章', '3.2 AEC-Q100 认证流程'],
            page_number: 18,
            snippet: '认证流程依据 AEC-Q100 分为四个阶段：晶圆级测试、封装级测试、可靠性认证与量产放行(PPAP)……',
            score: 0.92,
            bm25_score: 0.68,
            vector_score: 0.86,
            rrf_score: 0.77,
            rerank_score: 0.92,
          },
          {
            chunk_id: 'chunk-1',
            document_id: 'doc-41',
            document_title: '车规 eMMC 规格书（AEC-Q100）',
            heading_path: ['第 1 章', '1.1 产品概述'],
            page_number: 3,
            snippet: '车规 eMMC 5.1 依据 AEC-Q100 标准进行车规认证，温度等级分为 Grade 3/2/1/0……',
            score: 0.81,
            bm25_score: 0.55,
            vector_score: 0.79,
            rrf_score: 0.71,
            rerank_score: 0.81,
          },
          {
            chunk_id: 'chunk-3',
            document_id: 'doc-9',
            document_title: '供应商准入管理办法',
            heading_path: ['Sheet1', 'NAND Flash 供应商清单'],
            page_number: 1,
            snippet: 'NAND Flash 晶圆代工与封测合格供应商共 4 家：中芯国际、华虹半导体、长电科技、通富微电……',
            score: 0.34,
            bm25_score: 0.12,
            vector_score: 0.41,
            rrf_score: 0.28,
            rerank_score: 0.34,
          },
        ],
      },
      feedback: 'up',
      latency_ms: 312,
      cache_hit: false,
      created_at: iso(1),
    },
  ],
};

export const seedRetrievalExplain: RetrievalExplain = seedMessages['s-1'][1].retrieval!;

export const seedRetrievalResult: RetrievalResult = {
  query: '车规 eMMC AEC-Q100 认证流程',
  total_latency_ms: 312,
  cache_hit: false,
  chunks: seedRetrievalExplain.chunks,
  stages: seedRetrievalExplain.stages,
};

export const seedGraphData: GraphData = {
  nodes: [
    // ---- 存储产品 ----
    { id: 'n-product', label: '车规 eMMC 5.1', type: 'Product', properties: { 类别: '嵌入式存储', 车规等级: 'AEC-Q100 Grade 3', 容量: '8~128GB' }, source_chunks: 184 },
    { id: 'n-product2', label: '3D TLC NAND Flash', type: 'Product', properties: { 类别: 'NAND 晶圆', 堆叠: '128 层', 工艺: 'TLC' }, source_chunks: 142 },
    { id: 'n-product3', label: 'NVMe SSD 企业级', type: 'Product', properties: { 类别: '固态硬盘', 接口: 'PCIe Gen4 x4', 容量: '1.92~7.68TB' }, source_chunks: 96 },
    { id: 'n-product4', label: 'DDR5 DRAM', type: 'Product', properties: { 类别: 'DRAM 颗粒', 速率: 'DDR5-6400', 容量: '16Gb' }, source_chunks: 78 },
    { id: 'n-product5', label: 'UFS 4.0', type: 'Product', properties: { 类别: '嵌入式存储', 接口: 'UFS 4.0', 速率: '23.2Gbps' }, source_chunks: 64 },
    { id: 'n-product6', label: 'MicroSD 卡', type: 'Product', properties: { 类别: '存储卡', 标准: 'SD Express', 容量: '64~512GB' }, source_chunks: 52 },

    // ---- 部门 ----
    { id: 'n-dept-rd', label: '研发中心', type: 'Department', properties: { 编码: 'RD', 人数: 48 }, source_chunks: 30 },
    { id: 'n-dept-qa', label: '质量保证部', type: 'Department', properties: { 编码: 'QA', 人数: 20 }, source_chunks: 24 },
    { id: 'n-dept-proc', label: '采购部', type: 'Department', properties: { 编码: 'PROC', 人数: 9 }, source_chunks: 18 },
    { id: 'n-dept-compliance', label: '合规认证部', type: 'Department', properties: { 编码: 'CMP', 人数: 6 }, source_chunks: 22 },

    // ---- 人员 ----
    { id: 'n-person-li', label: '李强', type: 'Person', properties: { 角色: '编辑', 部门: '研发中心' }, source_chunks: 12 },
    { id: 'n-person-wang', label: '王敏', type: 'Person', properties: { 角色: '编辑', 部门: '质量保证部' }, source_chunks: 8 },
    { id: 'n-person-chen', label: '陈工', type: 'Person', properties: { 角色: '认证工程师', 部门: '合规认证部' }, source_chunks: 15 },
    { id: 'n-person-zhao', label: '赵磊', type: 'Person', properties: { 角色: '采购工程师', 部门: '采购部' }, source_chunks: 6 },

    // ---- 制度 ----
    { id: 'n-policy-reliability', label: '可靠性测试规范', type: 'Policy', properties: { 标准: 'AEC-Q100/JEDEC', 版本: '2026' }, source_chunks: 64 },
    { id: 'n-policy-risk', label: '供应链风险管理办法', type: 'Policy', properties: { 版本: '2026', 分级: 'I/II/III' }, source_chunks: 58 },
    { id: 'n-policy-export', label: '出口管制合规政策', type: 'Policy', properties: { 版本: '2026', 适用: '半导体存储' }, source_chunks: 41 },

    // ---- 供应商 (晶圆代工 / OSAT 封测) ----
    { id: 'n-sup-smic', label: '中芯国际', type: 'Supplier', properties: { 等级: 'A', 主供: 'NAND/DRAM 晶圆代工' }, source_chunks: 16 },
    { id: 'n-sup-hhgrace', label: '华虹半导体', type: 'Supplier', properties: { 等级: 'A', 主供: 'NAND 晶圆代工(二供)' }, source_chunks: 12 },
    { id: 'n-sup-jcet', label: '长电科技', type: 'Supplier', properties: { 等级: 'A', 主供: 'OSAT 封测' }, source_chunks: 10 },
    { id: 'n-sup-tfme', label: '通富微电', type: 'Supplier', properties: { 等级: 'A', 主供: 'OSAT 封测' }, source_chunks: 9 },

    // ---- 认证 (企业体系 / 产品准入) ----
    { id: 'n-cert-iso9001', label: 'ISO 9001', type: 'Certification', properties: { 机构: 'SGS', 到期: '2027-06' }, source_chunks: 28 },
    { id: 'n-cert-iso14001', label: 'ISO 14001', type: 'Certification', properties: { 机构: 'TUV', 到期: '2027-03' }, source_chunks: 20 },
    { id: 'n-cert-bsci', label: 'BSCI 社会责任', type: 'Certification', properties: { 机构: 'amfori', 到期: '2026-11' }, source_chunks: 24 },
    { id: 'n-cert-iatf', label: 'IATF 16949', type: 'Certification', properties: { 机构: 'TUV', 适用: '汽车供应链' }, source_chunks: 26 },
    { id: 'n-cert-aecq100', label: 'AEC-Q100', type: 'Certification', properties: { 适用: '车规集成电路', 等级: 'Grade 0~3' }, source_chunks: 32 },
    { id: 'n-cert-ce', label: 'CE 认证', type: 'Certification', properties: { 指令: 'LVD/EMC/RED', 到期: '长期' }, source_chunks: 35 },
    { id: 'n-cert-fcc', label: 'FCC 认证', type: 'Certification', properties: { 等级: 'SDoC', 到期: '长期' }, source_chunks: 18 },
    { id: 'n-cert-rohs', label: 'RoHS 2.0', type: 'Certification', properties: { 版本: '2011/65/EU', 到期: '长期' }, source_chunks: 16 },

    // ---- 专利 ----
    { id: 'n-pat-001', label: 'ZL202310458X 3D NAND 堆叠结构', type: 'Patent', properties: { 类型: '发明专利', 申请人: '研发中心' }, source_chunks: 14 },
    { id: 'n-pat-002', label: 'ZL202410112X eMMC 磨损均衡算法', type: 'Patent', properties: { 类型: '发明专利', 申请人: '研发中心' }, source_chunks: 11 },
  ],
  links: [
    // 产品 → 部门 (归属)
    { source: 'n-product', target: 'n-dept-rd', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-product2', target: 'n-dept-rd', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-product3', target: 'n-dept-rd', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-product4', target: 'n-dept-rd', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-product5', target: 'n-dept-rd', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-product6', target: 'n-dept-rd', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-product2', target: 'n-dept-proc', type: 'BELONGS_TO', weight: 1 },

    // 产品 → 供应商 (供货)
    { source: 'n-product2', target: 'n-sup-smic', type: 'SUPPLIES', weight: 3 },
    { source: 'n-product2', target: 'n-sup-hhgrace', type: 'SUPPLIES', weight: 2 },
    { source: 'n-product2', target: 'n-sup-jcet', type: 'SUPPLIES', weight: 2 },
    { source: 'n-product2', target: 'n-sup-tfme', type: 'SUPPLIES', weight: 1 },
    { source: 'n-product', target: 'n-sup-jcet', type: 'SUPPLIES', weight: 2 },
    { source: 'n-product', target: 'n-sup-tfme', type: 'SUPPLIES', weight: 1 },
    { source: 'n-product3', target: 'n-sup-smic', type: 'SUPPLIES', weight: 2 },

    // 产品 → 认证 (多跳: 产品经认证上市)
    { source: 'n-product', target: 'n-cert-aecq100', type: 'CERTIFIED_BY', weight: 3 },
    { source: 'n-product', target: 'n-cert-iatf', type: 'CERTIFIED_BY', weight: 2 },
    { source: 'n-product', target: 'n-cert-ce', type: 'CERTIFIED_BY', weight: 2 },
    { source: 'n-product', target: 'n-cert-rohs', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-product3', target: 'n-cert-ce', type: 'CERTIFIED_BY', weight: 2 },
    { source: 'n-product3', target: 'n-cert-fcc', type: 'CERTIFIED_BY', weight: 2 },
    { source: 'n-product3', target: 'n-cert-rohs', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-product5', target: 'n-cert-ce', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-product5', target: 'n-cert-fcc', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-product6', target: 'n-cert-ce', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-product6', target: 'n-cert-fcc', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-product6', target: 'n-cert-rohs', type: 'CERTIFIED_BY', weight: 1 },

    // 部门 → 认证 (审核/维持)
    { source: 'n-dept-qa', target: 'n-cert-iso9001', type: 'AUDITED_BY', weight: 2 },
    { source: 'n-dept-qa', target: 'n-cert-iso14001', type: 'AUDITED_BY', weight: 1 },
    { source: 'n-dept-compliance', target: 'n-cert-bsci', type: 'AUDITED_BY', weight: 2 },
    { source: 'n-dept-compliance', target: 'n-cert-ce', type: 'PARTICIPATES_IN', weight: 1 },
    { source: 'n-dept-compliance', target: 'n-cert-fcc', type: 'PARTICIPATES_IN', weight: 1 },

    // 供应商 → 认证 (供应商资质)
    { source: 'n-sup-smic', target: 'n-cert-iso9001', type: 'CERTIFIED_BY', weight: 2 },
    { source: 'n-sup-smic', target: 'n-cert-iatf', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-sup-jcet', target: 'n-cert-iso9001', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-sup-jcet', target: 'n-cert-iatf', type: 'CERTIFIED_BY', weight: 1 },
    { source: 'n-sup-tfme', target: 'n-cert-iso9001', type: 'CERTIFIED_BY', weight: 1 },

    // 产品 → 制度 (受约束)
    { source: 'n-product', target: 'n-policy-reliability', type: 'GOVERNED_BY', weight: 2 },
    { source: 'n-product2', target: 'n-policy-reliability', type: 'GOVERNED_BY', weight: 2 },
    { source: 'n-product3', target: 'n-policy-reliability', type: 'GOVERNED_BY', weight: 2 },
    { source: 'n-product3', target: 'n-policy-export', type: 'GOVERNED_BY', weight: 1 },
    { source: 'n-product5', target: 'n-policy-export', type: 'GOVERNED_BY', weight: 1 },
    { source: 'n-product', target: 'n-policy-risk', type: 'GOVERNED_BY', weight: 1 },
    { source: 'n-sup-smic', target: 'n-policy-risk', type: 'GOVERNED_BY', weight: 1 },

    // 产品 → 专利 (发明)
    { source: 'n-product2', target: 'n-pat-001', type: 'INVENTED_BY', weight: 1 },
    { source: 'n-product', target: 'n-pat-002', type: 'INVENTED_BY', weight: 1 },
    { source: 'n-product3', target: 'n-pat-001', type: 'REFERENCES', weight: 1 },

    // 人员 → 部门 (归属)
    { source: 'n-person-li', target: 'n-dept-rd', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-person-wang', target: 'n-dept-qa', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-person-chen', target: 'n-dept-compliance', type: 'BELONGS_TO', weight: 1 },
    { source: 'n-person-zhao', target: 'n-dept-proc', type: 'BELONGS_TO', weight: 1 },

    // 人员 → 制度/专利 (撰写/发明)
    { source: 'n-policy-reliability', target: 'n-dept-qa', type: 'AUTHORED_BY', weight: 1 },
    { source: 'n-policy-export', target: 'n-person-chen', type: 'AUTHORED_BY', weight: 1 },
    { source: 'n-pat-001', target: 'n-person-li', type: 'INVENTED_BY', weight: 1 },
    { source: 'n-pat-002', target: 'n-person-li', type: 'INVENTED_BY', weight: 1 },

    // 产品间引用 (存储器件组合关系)
    { source: 'n-product3', target: 'n-product2', type: 'REFERENCES', weight: 1 },
    { source: 'n-product', target: 'n-product2', type: 'REFERENCES', weight: 1 },
  ],
};

export const seedGraphStats: GraphStats = {
  node_count: seedGraphData.nodes.length,
  relation_count: seedGraphData.links.length,
  type_distribution: {
    Product: 6,
    Department: 4,
    Person: 4,
    Policy: 3,
    Supplier: 4,
    Certification: 8,
    Patent: 2,
  },
  relation_distribution: {
    BELONGS_TO: 11,
    MANUFACTURES: 0,
    CERTIFIED_BY: 17,
    SUPPLIES: 7,
    AUTHORED_BY: 2,
    REFERENCES: 3,
    GOVERNED_BY: 7,
    AUDITED_BY: 3,
    PARTICIPATES_IN: 2,
    INVENTED_BY: 4,
  },
};

export const seedGraphPath: GraphPathResult = {
  cypher:
    'MATCH (p:Product)-[:CERTIFIED_BY]->(c:Certification)\nWHERE c.label IN ["CE 认证","FCC 认证"]\nRETURN p.label, c.label ORDER BY p.label',
  records: [
    { product: '车规 eMMC 5.1', 认证: 'CE 认证', 机构: 'SGS' },
    { product: 'NVMe SSD 企业级', 认证: 'CE 认证', 机构: 'LVD/EMC 指令' },
    { product: 'NVMe SSD 企业级', 认证: 'FCC 认证', 机构: 'SDoC' },
    { product: 'UFS 4.0', 认证: 'CE 认证', 机构: 'EMC 指令' },
    { product: 'UFS 4.0', 认证: 'FCC 认证', 机构: 'SDoC' },
    { product: 'MicroSD 卡', 认证: 'CE 认证', 机构: 'LVD 指令' },
    { product: 'MicroSD 卡', 认证: 'FCC 认证', 机构: 'SDoC' },
  ],
  explanation:
    '4 款存储产品通过 CE/FCC 认证进入跨境市场，其中 NVMe SSD 企业级与 UFS 4.0 同时持有 CE+FCC 双认证，满足欧美双重准入要求；车规 eMMC 5.1 额外通过 AEC-Q100 车规认证进入车载前装市场。',
};

// 评估指标基于 backend/scripts/run_ablation.py 真实消融结果
// bm25_only / vector_only / rrf_fusion 为真实评估值 (32 样本, 改进评估集每查询 2-3 相关文档)
// rerank_only / full 为基于重排器预期提升的参考值 (待 bge-reranker 真实运行后校准)
export const seedEvalResults: EvalResult[] = [
  {
    strategy: 'bm25_only',
    description: '仅 BM25 关键词检索（稀疏）',
    metrics: { recall_at_5: 0.79, mrr: 0.9, ndcg_at_5: 0.83, precision_at_5: 0.32 },
    avg_latency_ms: 22,
    p50_latency_ms: 18,
    p95_latency_ms: 32,
    p99_latency_ms: 48,
  },
  {
    strategy: 'vector_only',
    description: '仅向量稠密检索（语义）',
    metrics: { recall_at_5: 0.78, mrr: 0.89, ndcg_at_5: 0.81, precision_at_5: 0.31 },
    avg_latency_ms: 52,
    p50_latency_ms: 42,
    p95_latency_ms: 68,
    p99_latency_ms: 95,
  },
  {
    strategy: 'rrf_fusion',
    description: 'BM25 + 向量 RRF 融合（无重排）',
    metrics: { recall_at_5: 0.78, mrr: 0.9, ndcg_at_5: 0.82, precision_at_5: 0.31 },
    avg_latency_ms: 72,
    p50_latency_ms: 58,
    p95_latency_ms: 89,
    p99_latency_ms: 128,
  },
  {
    strategy: 'rerank_only',
    description: '向量召回 + Cross-Encoder 重排',
    metrics: { recall_at_5: 0.79, mrr: 0.93, ndcg_at_5: 0.87, precision_at_5: 0.42 },
    avg_latency_ms: 138,
    p50_latency_ms: 112,
    p95_latency_ms: 168,
    p99_latency_ms: 235,
  },
  {
    strategy: 'full',
    description: 'RRF 融合 + Cross-Encoder 重排（完整管线）',
    metrics: { recall_at_5: 0.85, mrr: 0.95, ndcg_at_5: 0.91, precision_at_5: 0.52 },
    avg_latency_ms: 178,
    p50_latency_ms: 148,
    p95_latency_ms: 218,
    p99_latency_ms: 312,
  },
];

export const seedLatencyTrend: { date: string; value: number }[] = Array.from(
  { length: 14 },
  (_, i) => ({
    date: new Date(now - (13 - i) * day).toISOString().slice(0, 10),
    value: Math.round(280 + Math.sin(i / 2) * 60 + Math.random() * 40),
  })
);

export const seedSystemStats: SystemStats = {
  user_count: 89,
  document_count: 1247,
  session_count: 5630,
  retrieval_count: 48210,
  cache_hit_rate: 0.683,
  graph_node_count: 8420,
  parse_failed_count: 23,
  rate_limited_count: 142,
  trend: seedLatencyTrend,
};

export const seedAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    user_id: 'u-admin',
    user_name: '系统管理员',
    action: 'document.upload',
    resource_type: 'document',
    resource_id: 'doc-7',
    detail: '上传文档《ANSI/ESD S20.20 静电放电控制体系认证证书》',
    ip: '10.0.1.12',
    created_at: iso(0),
  },
  {
    id: 'log-2',
    user_id: 'u-li',
    user_name: '李强',
    action: 'qa.ask',
    resource_type: 'session',
    resource_id: 's-1',
    detail: '发起智能问答：车规 eMMC 5.1 AEC-Q100 认证流程',
    ip: '10.0.2.34',
    created_at: iso(0),
  },
  {
    id: 'log-3',
    user_id: 'u-wang',
    user_name: '王敏',
    action: 'document.delete',
    resource_type: 'document',
    resource_id: 'doc-x',
    detail: '删除过期文档《2023 供应商名录》',
    ip: '10.0.3.21',
    created_at: iso(1),
  },
  {
    id: 'log-4',
    user_id: 'u-admin',
    user_name: '系统管理员',
    action: 'user.disable',
    resource_type: 'user',
    resource_id: 'u-zhao',
    detail: '禁用用户 赵磊（离职）',
    ip: '10.0.1.12',
    created_at: iso(2),
  },
  {
    id: 'log-5',
    user_id: 'u-li',
    user_name: '李强',
    action: 'graph.query',
    resource_type: 'graph',
    resource_id: '-',
    detail: '图谱查询：车规 eMMC 认证供应商与 AEC-Q100 路径',
    ip: '10.0.2.34',
    created_at: iso(3),
  },
];

export const seedEvalDataset: EvalDatasetItem[] = [
  { id: 'q1', query: '车规 eMMC 5.1 的 AEC-Q100 认证流程', relevant_chunk_ids: ['chunk-2', 'chunk-1'], expected_answer: '四阶段：晶圆级测试、封装级测试、可靠性认证(HTOL/TC/uHAST)、量产放行(PPAP)', difficulty: 'medium' },
  { id: 'q2', query: 'NAND Flash 晶圆代工与封测供应商有哪些', relevant_chunk_ids: ['chunk-3'], expected_answer: '4 家：中芯国际、华虹半导体(晶圆代工)；长电科技、通富微电(OSAT 封测)', difficulty: 'easy' },
  { id: 'q3', query: '存储产品可靠性测试项目有哪些', relevant_chunk_ids: ['chunk-4'], expected_answer: '寿命测试(HTOL/TC)、环境测试(uHAST/THB)、机械测试(跌落/振动)，NVMe SSD 须额外做异常掉电测试', difficulty: 'medium' },
  { id: 'q4', query: '车规 eMMC 的工作温度等级', relevant_chunk_ids: ['chunk-1'], expected_answer: 'Grade 3(-40~85℃)、Grade 2(-40~105℃)、Grade 1(-40~125℃)、Grade 0(-40~150℃)，车规 eMMC 通常要求 Grade 3 及以上', difficulty: 'easy' },
  { id: 'q5', query: 'AEC-Q100 可靠性认证包含哪些测试', relevant_chunk_ids: ['chunk-2', 'chunk-4'], expected_answer: 'HTOL 高温工作寿命、TC 温度循环、uHAST 非饱和高压蒸煮、THB 温湿度偏压等，依据 AEC-Q100 与 JEDEC 标准', difficulty: 'hard' },
];

export interface IndustryCategory {
  id: string;
  name: string;
  icon: string; // lucide icon name
  doc_count: number;
  description: string;
  accent: string; // 主题色 (单色, 用于图标背景)
  tags: string[];
}

export const seedIndustries: IndustryCategory[] = [
  {
    id: 'enterprise',
    name: '企业知识库',
    icon: 'Building2',
    doc_count: 29,
    description: '半导体存储工厂体系认证、管理制度、流程规范、政策文件与内部通知',
    accent: 'indigo',
    tags: ['ISO 9001', 'IATF 16949', 'AEC-Q100', 'BSCI', 'QC 080000'],
  },
  {
    id: 'product',
    name: '产品知识库',
    icon: 'Package',
    doc_count: 22,
    description: 'NAND Flash、DRAM、eMMC、UFS、SSD、存储卡等半导体存储产品手册、技术规格与选型指南',
    accent: 'slate',
    tags: ['NAND Flash', 'DRAM', 'eMMC', 'UFS', 'SSD', '存储卡'],
  },
  {
    id: 'aftersales',
    name: '售后知识库',
    icon: 'Headphones',
    doc_count: 13,
    description: '售后 FAQ、保修条款、退换货流程、故障排查与客户服务规范',
    accent: 'emerald',
    tags: ['FAQ', '保修', '退换货', '故障代码', '服务规范'],
  },
];
